# Generated by Django 6.1 on 2026-09-01 13:53

import common.validators
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Letters, digits and . + - _ only. Not an email address or a number.', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Use letters, digits and . + - _ only. No @ or spaces.', regex='^[\\w.+-]+\\Z'), common.validators.validate_username_not_numeric], verbose_name='username')),
                ('email', models.EmailField(help_text='Required: password-reset links are sent here.', max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(help_text='Country code first, digits only, without +. For example 250788123456.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter the phone number with its country code, digits only, without +.', regex='^[1-9][0-9]{7,14}$')], verbose_name='phone number')),
                ('language', models.CharField(choices=[('en', 'English'), ('rw', 'Ikinyarwanda'), ('fr', 'Français')], default='en', max_length=2, verbose_name='language')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting an account.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_ci_unique', violation_error_message='A user with that username already exists.'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique', violation_error_message='A user with that email address already exists.')],
            },
        ),
    ]
