# Generated by Django 6.1 on 2026-09-02
#
# Two changes to one column, no data change:
#   * `models.CharField` -> `PhoneField`, which canonicalises every write and
#     every `=` lookup. Same column type and width, so this half emits no SQL.
#   * `null=True`, so erasure under Law 058/2021 (privacy ruling P-4) can clear
#     the number instead of inventing a stranger's. `blank=False` still makes a
#     phone mandatory of every account that is created.
#
# The only SQL is `ALTER TABLE accounts_user ALTER COLUMN phone DROP NOT NULL`,
# which PostgreSQL does as a catalogue update: no table rewrite, no scan, and
# the existing unique index is untouched (NULLs are distinct in one).

import apps.accounts.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=apps.accounts.models.PhoneField(help_text='Write it as 0788123456. A number from another country needs its country code, as +254712345678.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message="Write a Rwandan number as 0788123456, or another country's as +254712345678.", regex='^[1-9][0-9]{7,14}$')], verbose_name='phone number'),
        ),
    ]
