"""The test-only stand-ins get their public identifiers (ADR 0010).

`tests.testapp` is installed by `config.settings.test` only, so this migration
never reaches a real database - but it does reach `test_raporo`, which is why
it has to exist: `SoftDeleteModel` now carries `public_id`, and without this
every insert into a stand-in table fails with `column "public_id" of relation
"testapp_thing" does not exist`.

SAFE ONLINE, trivially: the table is created and dropped by the test runner.
See `apps/orgs/migrations/0002_public_id.py` for the real analysis of what
`AddField` on a unique callable-default column does and does not do.
"""

# Generated by Django 6.1 on 2026-09-02 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='sale',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='scopedthing',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='scopedthingownmeta',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='thing',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
    ]
