"""Initial audit schema.

`AuditLog.org` and `AuditLog.store` are both nullable (a system action may have
neither), but when both are present they must agree, so a composite foreign key
ties them to `orgs_store (id, org_id)`. Postgres MATCH SIMPLE semantics leave
the constraint unchecked when either column is NULL, which is exactly the
behaviour wanted here: org-only and store-only rows stay legal, while
`AuditLog.objects.create(org=org_a, store=<org_b store>)` - which bypasses the
check in `audit.services.record()` - is refused by the database.
"""

# Generated by Django 6.1 on 2026-09-01 13:53

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_action', message='An audit action looks like `user.created`: lowercase, dot-separated.', regex='^[a-z][a-z0-9_]*(\\.[a-z0-9_]+)+$')], verbose_name='action')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='target type')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='target id')),
                ('changes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='changes')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='at')),
                ('actor', models.ForeignKey(blank=True, help_text='Empty when the system acted on its own.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.organization', verbose_name='organization')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit entries',
                'ordering': ('-at', '-id'),
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['org', 'at'], name='audit_org_at_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx')],
            },
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE audit_auditlog ADD CONSTRAINT "
                "audit_auditlog_store_same_org_fk "
                "FOREIGN KEY (store_id, org_id) REFERENCES orgs_store (id, org_id) "
                "DEFERRABLE INITIALLY IMMEDIATE;"
            ),
            reverse_sql=(
                "ALTER TABLE audit_auditlog DROP CONSTRAINT IF EXISTS "
                "audit_auditlog_store_same_org_fk;"
            ),
        ),
    ]
