"""Initial orgs schema.

Beyond the tables, this migration installs three composite foreign keys so that
"these two rows belong to the same organization" is a database fact:

    orgs_membership (role_id, org_id)      -> orgs_role (id, org_id)
    orgs_storeaccess (membership_id, org_id) -> orgs_membership (id, org_id)
    orgs_storeaccess (store_id, org_id)    -> orgs_store (id, org_id)

`Membership.clean()` / `StoreAccess.clean()` check the same thing, but
`Model.objects.create()` never calls `clean()`, and the reviewed reproduction
created a membership holding another organization's role that way. The
`(id, org)` unique constraints above exist to be the targets of these keys.

Note on reversibility: everything here - including the partial-unique slug
constraint (`orgs_organization_unique_live_slug`) - is created by this one
migration, so `migrate orgs zero` drops the composite keys, then the constraints,
then the tables. No step can fail on existing data, because nothing survives to
conflict: reversing destroys every organization, store, role, membership and
store-access row. Back the data up first; there is no half-way state to land in.

And it destroys more than orgs. `audit.AuditLog` points at `orgs.Store`, so
Django's backwards plan for `migrate orgs zero` unapplies `audit.0002` and
`audit.0001` first: **the entire audit log goes with it**. That table is
append-only by database trigger precisely because the application may not remove
a single row from it, so this is the one command that can erase the forensic
record wholesale. `migrate orgs zero` is a development reset, never an operation
to run against anything that has ever served a request.
"""

# Generated by Django 6.1 on 2026-09-01 13:53

import apps.orgs.models
import common.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, upload_to=apps.orgs.models.organization_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'], code='invalid_image_extension', message='Upload a PNG, JPEG or WebP image.'), common.validators.validate_image_size, common.validators.validate_image_content], verbose_name='logo')),
                ('brand', models.JSONField(blank=True, default=dict, help_text="Colour and typography tokens for this organization's reports.", verbose_name='brand tokens')),
                ('base_currency', models.CharField(default='RWF', max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_currency', message='Enter a three-letter ISO 4217 currency code, for example RWF.', regex='^[A-Z]{3}$')], verbose_name='base currency')),
                ('timezone', models.CharField(default='Africa/Kigali', help_text='Reporting periods start and end in this zone.', max_length=64, validators=[common.validators.validate_timezone], verbose_name='time zone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='permissions')),
                ('is_preset', models.BooleanField(default=False, verbose_name='preset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='orgs.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='orgs.organization', verbose_name='organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='orgs.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('brand', models.JSONField(blank=True, default=dict, help_text='Used only when this store uses its own branding.', verbose_name='brand tokens')),
                ('use_own_branding', models.BooleanField(default=False, help_text="Off: inherit the organization's branding entirely.", verbose_name='use its own branding')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='orgs.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StoreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_access', to='orgs.membership', verbose_name='membership')),
                ('org', models.ForeignKey(help_text='Denormalized from the membership so the database can enforce it.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.organization', verbose_name='organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access', to='orgs.store', verbose_name='store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'store access',
                'verbose_name_plural': 'store access',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='orgs_organization_unique_live_slug', violation_error_message='That URL slug is taken.'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org', 'name'), name='orgs_role_unique_live_name_per_org', violation_error_message='This organization already has a role with that name.'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('id', 'org'), name='orgs_role_id_org_uniq'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'org'), name='orgs_membership_unique_live_user_per_org', violation_error_message='This person is already a member of this organization.'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('id', 'org'), name='orgs_membership_id_org_uniq'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org', 'name'), name='orgs_store_unique_live_name_per_org', violation_error_message='This organization already has a store with that name.'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('id', 'org'), name='orgs_store_id_org_uniq'),
        ),
        migrations.AddConstraint(
            model_name='storeaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('membership', 'store'), name='orgs_storeaccess_unique_live_membership_store', violation_error_message='This member already has access to that store.'),
        ),
        # --- composite foreign keys: same-organization, enforced by Postgres ---
        migrations.RunSQL(
            sql=(
                "ALTER TABLE orgs_membership ADD CONSTRAINT "
                "orgs_membership_role_same_org_fk "
                "FOREIGN KEY (role_id, org_id) REFERENCES orgs_role (id, org_id) "
                "DEFERRABLE INITIALLY IMMEDIATE;"
            ),
            reverse_sql=(
                "ALTER TABLE orgs_membership DROP CONSTRAINT IF EXISTS "
                "orgs_membership_role_same_org_fk;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE orgs_storeaccess ADD CONSTRAINT "
                "orgs_storeaccess_membership_same_org_fk "
                "FOREIGN KEY (membership_id, org_id) "
                "REFERENCES orgs_membership (id, org_id) "
                "DEFERRABLE INITIALLY IMMEDIATE;"
            ),
            reverse_sql=(
                "ALTER TABLE orgs_storeaccess DROP CONSTRAINT IF EXISTS "
                "orgs_storeaccess_membership_same_org_fk;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE orgs_storeaccess ADD CONSTRAINT "
                "orgs_storeaccess_store_same_org_fk "
                "FOREIGN KEY (store_id, org_id) REFERENCES orgs_store (id, org_id) "
                "DEFERRABLE INITIALLY IMMEDIATE;"
            ),
            reverse_sql=(
                "ALTER TABLE orgs_storeaccess DROP CONSTRAINT IF EXISTS "
                "orgs_storeaccess_store_same_org_fk;"
            ),
        ),
    ]
