"""The tenancy spine gets its public identifiers (ADR 0010).

All five org-level tables, including **both** `Organization` and `Store`.
`Organization.slug` is not a substitute: its unique constraint is
conditioned on live rows by design — a soft-deleted organization releases
its slug — so it is neither stable nor unique over time, and it is mutable
and user-chosen. `Store` has no slug at all.

**SAFE ONLINE — and only because every table in every environment is empty.**

`AddField` on a unique field with a *callable* default is not the four-step
dance, and this is the one moment in the project's life when it does not have
to be. Django resolves the callable **once** and emits a single literal for the
whole table (verified with `sqlmigrate`):

    ALTER TABLE "orgs_store" ADD COLUMN "public_id" uuid
        DEFAULT '<one literal uuid>'::uuid NOT NULL UNIQUE;
    ALTER TABLE "orgs_store" ALTER COLUMN "public_id" DROP DEFAULT;

Two consequences worth being explicit about, because the second one is why
this ships as one migration:

* a **constant** default does not rewrite the table (measured on PG 18.6:
  `pg_relation_filenode` unchanged, unlike a volatile default), so the
  `AccessExclusiveLock` is held for a moment rather than for a rewrite; the
  inline `UNIQUE` builds its index in the same statement, which on an empty
  table is instant;
* on a table holding **two or more rows** this statement fails outright, and
  measured rather than assumed — two `orgs_organization` rows, then `migrate`:

      django.db.utils.IntegrityError: could not create unique index
      "orgs_organization_public_id_key"
      DETAIL:  Key (public_id)=(01a06292-...) is duplicated.

  The migration is atomic, so the column is **not** left behind (checked:
  `information_schema.columns` reports none afterwards) and the database is not
  half-migrated. There is no silent-wrong outcome to guard against, which is
  why this migration carries no row-count assertion.

  That error text is also where the index name shows up, and it is the answer
  to "does `unique=True` cost us a readable constraint name?" — PostgreSQL
  names it `<table>_public_id_key`, which names the column an operator needs.

The recipe if this ever has to be applied to a populated table (do not edit
this migration; write a new one): add the column **nullable with no default**;
backfill in batches with `RunPython`, one UUID per row; `ADD CONSTRAINT ...
CHECK (public_id IS NOT NULL) NOT VALID` → `VALIDATE CONSTRAINT` → `SET NOT
NULL` → drop the CHECK (measured: 2.8 ms on 300 000 rows after a validated
CHECK, versus a full scan without one); then `CREATE UNIQUE INDEX
CONCURRENTLY` in a migration with `atomic = False`. That is four steps and a
rehearsed rollback; this is one `AddField`. The asymmetry is the whole argument
for landing the column now — `ALTER TABLE ADD COLUMN ... DEFAULT <volatile>` on
a 200 000-row table rewrote the table under `AccessExclusiveLock` when measured.

No `RunSQL`: nothing here is frozen text, so the SHA-256 pins in
`tests/test_db_stability.py` are untouched (asserted, not assumed — that
module's scan walks every migration this repo ships).
"""

# Generated by Django 6.1 on 2026-09-02 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='organization',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='role',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='store',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
        migrations.AddField(
            model_name='storeaccess',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='public id'),
        ),
    ]
